// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  chantsSidebar: [
    {
      type: 'doc',
      id: 'chants/repertoire',
      label: 'Répertoire',
    },
    {
      type: 'autogenerated',
      dirName: 'chants',
    },
  ],
  programmesSidebar: [
    {
      type: 'doc',
      id: 'programmes/liste-programmes',
      label: 'Tous les programmes',
    },
    {
      type: 'autogenerated',
      dirName: 'programmes',
    },
  ],
  choraleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'vie-de-la-chorale',
    },
  ],
  tutorielsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutoriels',
    },
  ],
};

export default sidebars;
